/*==============================================================*/
/* DBMS name:      ORACLE Version 11g                           */
/* Created on:     2016.09.05 14:17:43                          */
/*==============================================================*/


CREATE TABLESPACE TS_BASEDATA
DATAFILE 'TS_BASEDATA'
SIZE 100M
 AUTOEXTEND ON
    NEXT 10M
    MAXSIZE UNLIMITED;

CREATE TABLESPACE TS_HIS
DATAFILE 'TS_HIS'
SIZE 50M
 AUTOEXTEND ON
    NEXT 10M
    MAXSIZE UNLIMITED;

CREATE TABLESPACE TS_INDEX
DATAFILE 'TS_INDEX'
SIZE 50M
 AUTOEXTEND ON
    NEXT 10M
    MAXSIZE UNLIMITED;

CREATE TABLESPACE TS_SCHEDULER
DATAFILE 'TS_SCHEDULER'
SIZE 100M
 AUTOEXTEND ON
    NEXT 10M
    MAXSIZE UNLIMITED;

CREATE TABLESPACE TS_SYS
DATAFILE 'TS_SYS'
SIZE 100M
 AUTOEXTEND ON
    NEXT 10M
    MAXSIZE UNLIMITED;

CREATE TABLESPACE TS_YWHD
DATAFILE 'TS_YWHD'
SIZE 500M
 AUTOEXTEND ON
    NEXT 20M
    MAXSIZE UNLIMITED;
	
CREATE TABLESPACE TS_OS_YWHD
DATAFILE 'TS_OS_YWHD'
SIZE 500M
 AUTOEXTEND ON
    NEXT 20M
    MAXSIZE UNLIMITED;