insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('000','index','首页','Home',  2  ,'0',  null  ,'index','','05','','AMEMS');


insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040','quality','质量管理','Quality',  1  ,'0',  null  ,'','','40','icon-trophy','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040010','quality:010','手册管理','Manual',  1  ,'040',  10  ,'','','','icon-folder-open-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040010010','maintenance:maintenancemanuals:manage','文档管理','Document Management',  2  ,'040010',  10  ,'maintenance/maintenancemanuals/manage','','','','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040030','quality:030','航空器证照管理','TC PC AC',  1  ,'040',  30  ,'','','','icon-camera','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040030010','quality:radiolicense:main','飞机三证监控','A/C License Monitor',  2  ,'040030',  10  ,'quality/radiolicense/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040101','quality:toolcheck:main','工具/设备校验','Tools/Device Check',  2  ,'040',  101  ,'quality/toolcheck/main','','','icon-bolt','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050','aerialmaterial','航材工具管理','Air Material And Tools',  1  ,'0',  null  ,'','','50','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050010','aerialmaterial:010','航材库存','Stock',  1  ,'050',  10  ,'','','','icon-building','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050010040','aerialmaterial:stockwarning:main','库存预警','Stock Early Warning',  2  ,'050010',  40  ,'aerialmaterial/stockwarning/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050010050','aerialmaterial:stock:main','库存查询','Stock Search',  2  ,'050010',  50  ,'aerialmaterial/stock/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050010060','otheraerocade:stock:main','其他飞行队库存查询','Other Aerocade Stock Search',  2  ,'050010',  60  ,'otheraerocade/stock/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050010070','aerialmaterial:removepart:main','拆下件清单','Remove Part List',  2  ,'050010',  70  ,'aerialmaterial/removepart/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050020','aerialmaterial:020','出入库管理','Stock In/Out',  1  ,'050',  20  ,'','','','icon-exchange','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050020020','aerialmaterial:outstock:main','出库管理','Stock Out',  2  ,'050020',  20  ,'aerialmaterial/outstock/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050020030','aerialmaterial:requisition:main','领料申请','Material Requisition',  2  ,'050020',  30  ,'aerialmaterial/requisition/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050020040','aerialmaterial:stock:iolist','出入库清单','Stock I/O List',  2  ,'050020',  40  ,'aerialmaterial/stock/iolist','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050010010','aerialmaterial:transfer:main','移库','Transfer',  2  ,'050020',  50  ,'aerialmaterial/transfer/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050010020','aerialmaterial:takestock:main','盘点','Take Stock',  2  ,'050020',  60  ,'aerialmaterial/takestock/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050010030','aerialmaterial:takestock:history','盘点历史','Take Stock History',  2  ,'050020',  70  ,'aerialmaterial/takestock/history','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050030','aerialmaterial:030','航材/工具采购管理','Material Purchase',  1  ,'050',  30  ,'','','','icon-shopping-cart','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050030010','aerialmaterial:reserve:manage','航材/工具提订申请','Request For Application',  2  ,'050030',  10  ,'aerialmaterial/reserve/manage','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050030020','aerialmaterial:reserve:approve','航材/工具提订确认','Confirmation Of Order',  2  ,'050030',  20  ,'aerialmaterial/reserve/approve','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050040','aerialmaterial:040','部件/工具送修记录','Material Repair',  1  ,'050',  40  ,'','','','icon-wrench','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050040010','aerialmaterial:repair:manage','航材/工具送修申请','Repair Application ',  2  ,'050040',  10  ,'aerialmaterial/repair/manage','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050040020','aerialmaterial:repair:approve','航材/工具送修确认','Repair Confirmation ',  2  ,'050040',  20  ,'aerialmaterial/repair/approve','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050070','aerialmaterial:03','航材借用','Airmaterial Borrow',  1  ,'050',  70  ,'','','','icon-signout','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050070010','aerialmaterial:secondment:main','借调对象维护','Seconded Object',  2  ,'050070',  10  ,'aerialmaterial/secondment/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050070020','aerialmaterial:borrow:main','借入申请','Borrow Apply',  2  ,'050070',  20  ,'aerialmaterial/borrow/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050070030','otheraerocade:borrow:main','其他飞行队借入申请','Other Aerocade Borrow Apply',  2  ,'050070',  30  ,'otheraerocade/borrow/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050070040','otheraerocade:outstock:main','其他飞行队借入归还出库单','Other Aerocade Borrow Return List',  2  ,'050070',  40  ,'otheraerocade/outstock/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050070050','aerialmaterial:secondment:notreturn','借调未归还统计','Secondment Did Not Return Statistics',  2  ,'050070',  50  ,'aerialmaterial/secondment/notreturn','','','','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050100','aerialmaterial:02','询价/合同管理','Enquiry/Contract',  1  ,'050',  100  ,'','','','icon-folder-open-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050100010','aerialmaterial:enquiry:main','询价管理','Enquiry',  2  ,'050100',  10  ,'aerialmaterial/enquiry/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050100020','aerialmaterial:contract:main','合同管理','Contract',  2  ,'050100',  20  ,'aerialmaterial/contract/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050120','aerialmaterial:100','工具借用记录','Tool Borrow',  1  ,'050',  120  ,'','','','icon-circle-arrow-right','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050120010','outfield:toolsuse:main','工具/设备借用','Tools/Device Use',  2  ,'050120',  10  ,'outfield/toolsuse/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050120020','outfield:toolsquick:main','工具快速借用/归还','Quick borrowing/restitution',  2  ,'050120',  20  ,'outfield/toolsquick/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050130','aerialmaterial:110','航材工具付款','Payment',  1  ,'050',  130  ,'','','','icon-tags','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050130010','aerialmaterial:contract:statistics','付款统计','Pay Statistics',  2  ,'050130',  10  ,'aerialmaterial/contract/statistics','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050140','aerialmaterial:05','航材成本管理','Materiel Cost',  1  ,'050',  140  ,'','','','icon-dollar','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050140010','aerialmaterial:cost:main','航材成本维护','Air Material Cost',  2  ,'050140',  10  ,'aerialmaterial/cost/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050140020','aerialmaterial:requisitioncost:main','单机领用成本','Requisition Cost',  2  ,'050140',  20  ,'aerialmaterial/requisitioncost/main','','','','AMEMS');


insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('110','airportensure','机场保障','Airport Security',  1  ,'0',  null  ,'','','75','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('110010','airportensure:maintenancerecord:main','设施维修','Maintenance Record',  2  ,'110',  10  ,'airportensure/maintenancerecord/main','','','icon-wrench','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('110020','airportensure:routinginspectionrecord:main','巡检记录','Routing Inspection Record',  2  ,'110',  20  ,'airportensure/routinginspectionrecord/main','','','icon-reorder','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('110030','airportensure:fuelup:main','飞机加油单','Fuel Up Record',  2  ,'110',  30  ,'airportensure/fuelup/main','','','icon-file-text','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('110040','airportensure:oilprice:main','油品价格维护','Oil Price',  2  ,'110',  40  ,'airportensure/oilprice/main','','','icon-tint','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('110050','airportensure:fuelup:statistics','油量统计','Oil Statistics',  2  ,'110',  50  ,'airportensure/fuelup/statistics','','','icon-bar-chart','AMEMS');



insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080','basedata','基础数据','Base Data',  1  ,'0',  null  ,'','','80','icon-th','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080010','project:fixchapter:main','ATA章节维护','ATA Maintenance',  2  ,'080',  10  ,'project/fixchapter/main','','','icon-file-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080020','material:material:main','部件主数据','Parts Main Data',  2  ,'080',  20  ,'material/material/main','','','icon-list-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080021','material:materialapply:main','部件主数据申请','Parts Apply',  2  ,'080',  21  ,'material/materialapply/main','','','icon-list-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080022','material:materialaudit:main','部件主数据审核','Parts Auditing',  2  ,'080',  22  ,'material/materialauditmain','','','icon-list-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080030','material:store:main','仓库主数据','Warehouse Main Data',  2  ,'080',  30  ,'material/store/main','','','icon-reorder','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080035','material:store2:main','仓库数据管理','Warehouse Main Data',  2  ,'080',  35  ,'material/store2/main','','适用新航材模块','icon-reorder','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080040','sys:base:main','基地维护','Base Maintenance',  2  ,'080',  40  ,'sys/base/main','','','icon-wrench','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('090','sys','系统管理','System Management',  1  ,'0',  null  ,'','','90','icon-cog','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('090010','sys:account:main','账号管理','Account Management',  2  ,'090',  10  ,'sys/account/main','','','icon-lock','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('090020','sys:user:main','用户管理','User Management',  2  ,'090',  20  ,'sys/user/main','','','icon-user','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('090030','sys:department:main','组织机构管理','Organization Management ',  2  ,'090',  30  ,'sys/department/main ','','','icon-group','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('090040','sys:role:main','角色管理','Role Management',  2  ,'090',  40  ,'sys/role/main','','','icon-user','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('090050','sys:menu:main','菜单管理','Menu Management',  2  ,'090',  50  ,'sys/menu/main','','','icon-list-ul','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('090060','sys:button:main','按钮管理','Button Management',  2  ,'090',  60  ,'sys/button/main','','','icon-th-large','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('090080','remotesystem:schedule','任务调度','Schedule',  2  ,'090',  80  ,'remotesystem/schedule','','','icon-tasks','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('090090','sys:message:main','消息管理','Message',  2  ,'090',  90  ,'sys/message/main','','','icon-bullhorn','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('090120','sys:log:main','登录日志','Login Log',2,'090',120,'sys/log/main','1','icon-file-text-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('090130','sys:loginlimit:main','登录限制','Login Limit',2,'090',130,'sys/loginlimit/main','','icon-minus-sign','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('090001','sys:settings:main','系统设置','System Setting',  2  ,'090',  1  ,'sys/settings/main','','','icon-gear','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('090003','sys:saibong:main','采番规则','Rules Of Number Assignment',2,'090',3,'sys/saibong/main','','icon-sort-by-order','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('090005','sys:monitorsettings:main','监控设置','Monitor Setting',2,'090',5,'sys/monitorsettings/main','','icon-cogs','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('090007','sys:dict:main','数据字典','Data Dictionary',2,'090',7,'sys/dict/main','','icon-book','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('080050','basedata:oil:main','油品规格','Oil',2,'080',50,'basedata/oil/main','','icon-tint','AMEMS');


insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050020005','aerialmaterial:receipt:main','收货管理','Receipt',  2  ,'050020',  5  ,'aerialmaterial/receipt/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050020007','aerialmaterial:godown:main','入库管理','Stock In',  2  ,'050020',  7  ,'aerialmaterial/godown/main','','','','AMEMS');


insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040090020','aerialmaterial:inspection:main','航材检验','Quality Testing',  2  ,'040',  90  ,'aerialmaterial/inspection/main','','','icon-bug','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040090025','material:inspection:main','航材/工具检验','Quality Testing',  2  ,'040',  95  ,'material/inspection/main','','','icon-bug','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050020090','aerialmaterial:stock:editmain','库存信息修改','Edit Stock Info',  2  ,'050020',  90  ,'aerialmaterial/stock/editmain','','','','AMEMS');



insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040170','quality:170','自我质量管理','Self-quality',  1  ,'040',  170  ,'','','','icon-user-md','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040170030','quality:annualplan:main','年度计划','Annual Plan',  2  ,'040170',  30  ,'quality/annualplan/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040170040','quality:annualplan:audit','审核年度计划','Audit Annual Plan',  2  ,'040170',  40  ,'quality/annualplan/audit','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040170050','quality:annualplan:approval','批准年度计划','Approval Annual Plan',  2  ,'040170',  50  ,'quality/annualplan/approval','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040170060','quality:auditnotice:main','创建审核通知单','Create Audit Notice',  2  ,'040170',  60  ,'quality/auditnotice/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040170070','quality:auditnoticequery:main','审核通知单','Audit Notice',  2  ,'040170',  70  ,'quality/auditnoticequery/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040170080','quality:audititemlist:main','创建审核项目单','Create Audit Item List',  2  ,'040170',  80  ,'quality/audititemlist/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040170090','quality:audititemlistquery:main','审核项目单','Audit Item List',  2  ,'040170',  90  ,'quality/audititemlistquery/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040170100','quality:noticeofdiscovery:main','发现问题通知单','Notice Of Discovery',  2  ,'040170',  100  ,'quality/noticeofdiscovery/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040170110','quality:correctivemeasures:main','问题整改措施','Corrective Measures',  2  ,'040170',  110  ,'quality/correctivemeasures/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040170120','quality:rectifymeasuresfollow:main','整改措施评估','Rectify Measures Assessment',  2  ,'040170',  120  ,'quality/rectifymeasuresfollow/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040170130','quality:qualityreviewreport:main','质量审核报告','Quality Review Report Manage',  2  ,'040170',  130  ,'quality/qualityreviewreport/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040170140','quality:qualityreviewreportquery:main','查看质量审核报告','Quality Review Report',  2  ,'040170',  140  ,'quality/qualityreviewreportquery/main','','','','AMEMS');


insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040180','maintenance:maintenancemanuals:manage1','质量文档管理','Document Management',  2  ,'040',  180  ,'maintenance/maintenancemanuals/manage1','','','icon-folder-open-alt','AMEMS');


insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080060','sys:contactperson:manage','联系人管理','Contacts',  2  ,'080',  60  ,'sys/contactperson/manage','','','icon-user','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040190','quality:190','供应商管理','Supplier',  1  ,'040',  190  ,'','','','icon-group','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040190010','aerialmaterial:aerialmaterialfirm:main','航材供应商管理','Aerialmaterial Supplier',  2  ,'040190',  10  ,'aerialmaterial/aerialmaterialfirm/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040190020','aerialmaterial:outsourcingfirm:main','承修商管理','Contractor',  2  ,'040190',  20  ,'aerialmaterial/outsourcingfirm/main','','','','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080025','basic:substitution:main','等效替代管理','The Equivalent Substitution',  2  ,'080',  25  ,'basic/substitution/main','','','icon-link','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050020006','aerialmaterial:returnedpurchase:manage','退货管理','Return',  2  ,'050020',  6  ,'aerialmaterial/returnedpurchase/manage','','','','AMEMS');


insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050090','aerialmaterial:080','航材报废管理','Scrapped Mgnt',  1  ,'050',  90  ,'','','','icon-trash','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050090010','aerialmaterial:scrap:apply','报废申请','Scrapped Apply',  2  ,'050090',  10  ,'aerialmaterial/scrap/apply','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050090020','aerialmaterial:scrap:audit','报废审核','Scrapped Audit',  2  ,'050090',  20  ,'aerialmaterial/scrap/audit','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050090030','aerialmaterial:scrappedlist:main','报废清单','Scrapped List',  2  ,'050090',  30  ,'aerialmaterial/scrappedlist/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050090040','aerialmaterial:destruction:main','销毁','Destruction',  2  ,'050090',  40  ,'aerialmaterial/destruction/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('050090050','aerialmaterial:destructionlist:main','销毁清单','Destruction List',  2  ,'050090',  50  ,'aerialmaterial/destructionlist/main','','','','AMEMS');


--培训管理
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030','training','培训管理','Training',  1  ,'0',  null  ,'','','30','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030010','training:course:main','课程管理','Course',  2  ,'030',  10  ,'training/course/main','','','icon-book','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030020','training:programme:main','培训大纲','Training Programme',  2  ,'030',  20  ,'training/programme/main','','','icon-sitemap','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030030','quality:maintenancepersonnel:manage','维修技术人员档案','Personnel Archives',  2  ,'030',  30  ,'quality/maintenancepersonnel/manage','','','icon-archive','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030035','training:faculty:main','教员管理','Lecturer',  2  ,'030',  35  ,'training/faculty/main','','','icon-male','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030040','training:plan:main','培训计划','Training Plan',  2  ,'030',  40  ,'training/plan/main','','','icon-calendar','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030050','training:trainingnotice:manage','培训通知','Training Notice',  2  ,'030',  50  ,'training/trainingnotice/manage','','','icon-bell-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030060','training:course:records','课程培训记录','Course Records',  2  ,'030',  60  ,'training/course/records','','','icon-file-text-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030070','training:record:main','维修人员培训记录','Personnel Training Records',  2  ,'030',  70  ,'training/record/main','','','icon-list-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030080','training:tracking:main','维修人员培训跟踪','Personnel Training Tracking',  2  ,'030',  80  ,'training/tracking/main','','','icon-bullseye','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030085','training:posttracking:main','岗位人员课程跟踪','Post Course Tracking',  2  ,'030',  85  ,'training/posttracking/main','','','icon-bullseye','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030087','training:testing:main','维修人员培训检测','Training Testing',  2  ,'030',  87  ,'training/testing/main','','','icon-bullseye','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030090','training:090','执照有效监控','License Valid Monitor',  1  ,'030',  90  ,'','','','icon-camera','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030090010','quality:authorizationmonitor:main','维修执照监控','Maintenance License Monitor',  2  ,'030090',  10  ,'quality/authorizationmonitor/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('030090020','quality:planemonitor:main','机型执照监控','Model Expiration Monitor',  2  ,'030090',  20  ,'quality/planemonitor/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('030900','training:file:zlmain','文档管理','Document Management',2,'030',990,'training/file/zlmain','','icon-archive','AMEMS');



--新工程技术
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015','project2','工程技术','Engineering Technology',1,'0',null,'','15','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015020040','project2:todo:main','待办事宜','To Do',2,'015',5,'project2/todo/main','','icon-calendar','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015010','project2:airworthiness:main','适航性资料','Airworthiness Data',2,'015',10,'project2/airworthiness/main','','icon-file-text','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015020','project2:assessment','工程评估','Engineering Assessment',1,'015',20,'','','icon-edit-sign','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015020010','project2:assessment:main','技术评估','Technical Assessment',2,'015020',10,'project2/assessment/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015020015','project2:assessment:view:main','技术评估列表','Technical Assessment List',2,'015020',15,'project2/assessment/view/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015020020','project2:assessment:audit:main','技术评估审核','Technical Assessment Audit',2,'015020',20,'project2/assessment/audit/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015020030','project2:assessment:approval:main','技术评估批准','Technology Assessment Approval',2,'015020',30,'project2/assessment/approval/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015030','project2:eo:main','工程指令','Engineering Order',2,'015',30,'project2/eo/main','','icon-hand-right','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015031','project2:production:main','生产指令','Production Order',2,'015',31,'project2/production/main','','icon-hand-right','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015040010','project2:bulletin:main','维护提示','MT',2,'015',42,'project2/bulletin/main','','icon-warning-sign','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015040015','project2:instruction:main','技术指令','Technical Order',2,'015',44,'project2/instruction/main','','icon-hand-right','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015040020','project2:bulletin:circulation:main','传阅','Redlining',2,'015',46,'project2/bulletin/circulation/main','','icon-eye-open','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015050','project2:airworthiness:monitoring:main','CAD监控','CAD Monitor',2,'015',50,'project2/airworthiness/monitoring/main','','iconnew-monitoring navigation-monitoring','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015055','project2:airworthiness:admonitoring:main','AD监控','AD Monitor',2,'015',55,'project2/airworthiness/admonitoring/main','','iconnew-monitoring navigation-monitoring','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015060','project2:maintenance','维修方案','Maintenance Program',1,'015',60,'','','icon-book','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015060010','project2:actype:main','机型设置','A/C Type Setting',2,'015060',10,'project2/actype/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015060020','project:maintenanceclass:main','维修项目大类','Maintenance Item Category',2,'015060',20,'project/maintenanceclass/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015060030','project2:maintenanceproject:main','维修方案','Maintenance Program',2,'015060',30,'project2/maintenanceproject/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015060040','project2:maintenanceproject:audit:main','维修方案审核','Maintenance Program Audit',2,'015060',40,'project2/maintenanceproject/audit/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015060050','project2:maintenanceproject:approval:main','维修方案批准','Maintenance Program Approval',2,'015060',50,'project2/maintenanceproject/approval/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015060060','project2:maintenanceproject:effect:main','维修方案生效确认','Maintenance Program Effect',2,'015060',60,'project2/maintenanceproject/effect/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015070','project2:workcard:main','工卡管理','Work Card Mgmt',2,'015',70,'project2/workcard/main','','icon-credit-card','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015080','project2:mel','MEL','MEL',1,'015',80,'','','icon-list-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015080010','project2:mel:main','MEL更改单','MEL Change Form',2,'015080',10,'project2/mel/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015080020','project2:meldetail:main','MEL清单','MEL',2,'015080',20,'project2/meldetail/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015090','project2:oil:consumption:monitor','滑油消耗监控','Lube Oil Consumption Monitoring',1,'015',90,'','','icon-bar-chart','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015090010','project2:oil:consumption:monitor:engine','发动机监控','Engine Monitoring',2,'015090',10,'project2/oil/consumption/monitor/engine','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015090020','project2:oil:consumption:monitor:apu','APU监控','APU Monitoring',2,'015090',20,'project2/oil/consumption/monitor/apu','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('015100','project2:document:main','工程文件管理','Documents Mgmt',2,'015',100,'project2/document/main','','icon-folder-open','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('010140','project:shapestructurerepair','结构修理/外形缺损','Structural And Shape',  1  ,'015',  110  ,'','','','icon-wrench','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('010140010','project:shapestructurerepair:main1','结构修理','Structural Repair',  2  ,'010140',  10  ,'project/shapestructurerepair/main1','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('010140020','project:shapestructurerepair:main','外形缺损','Shape Defect',  2  ,'010140',  20  ,'project/shapestructurerepair/main','','','','AMEMS');


delete from t_menu where id in ('040020010', '040150010');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,XTLX) values('010145','project:mel:main','MEL更改单','MEL Change Form',2,'010',145,'project/mel/main','','icon-list-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('010150','engineering:mel:main','MEL清单','MEL',  2  ,'010',  150  ,'engineering/mel/main','','','icon-file-text','AMEMS');

--基础数据
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080045','training:business:manage','岗位管理','Post',  2  ,'080',  45  ,'training/business/manage','','','icon-group','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080070','basic:zone:main','区域管理','Zone',  2  ,'080',  70  ,'basic/zone/main','','','icon-map-marker','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080080','basic:station:main','飞机站位管理','Station',  2  ,'080',  80  ,'basic/station/main','','','icon-plane','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080090','basic:coverplateinformation:main','盖板管理','Cover Plate',  2  ,'080',  90  ,'basic/coverplateinformation/main','','','icon-inbox','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080100','basic:stage:main','阶段管理','Stage',  2  ,'080',  100  ,'basic/stage/main','','','icon-list-ol','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('090035','sys:workgroup:main','工作组管理','Workgroup Management',2,'080',110,'sys/workgroup/main','','icon-group','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('080120','basic:propertyright:main','产权数据管理','Property Right Management',  2  ,'080',  120  ,'basic/propertyright/main','','','icon-adn','AMEMS');

--新航材/工具管理
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055010','material:stock:material','航材库存','Material Stock',	1	,'055',	10	,'','','icon-building','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055010010','material:stock:material:inside','库内查询','Inside Stock',	2	,'055010',	10	,'material/stock/material/inside','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055010020','material:stock:material:outside','库外查询','Outside Stock',	2	,'055010',	20	,'material/stock/material/outside','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055010030','material:stock:material:detail','库存明细账','Inventory Account',	2	,'055010',	30	,'material/stock/material/detail','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055015','material:stock:tool','工具库存','Tool Stock',	1	,'055',	15	,'','','icon-wrench','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055015010','material:stock:tool:inside','库内查询','Inside Stock',	2	,'055015',	10	,'material/stock/tool/inside','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055015015','material:stock:tool:insideut','库存查询','Inside Stock',	2	,'055015',	15	,'material/stock/tool/insideut','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055015020','material:stock:tool:outside','库外查询','Outside Stock',	2	,'055015',	20	,'material/stock/tool/outside','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055015030','material:stock:tool:detail','库存明细账','Inventory Account',	2	,'055015',	30	,'material/stock/tool/detail','','','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055','material','航材工具管理','Air Material And Tool',	1	,'0',	55	,'','55','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055050','material:demand','需求管理','Demand MGNT',	1	,'055',	50	,'','','icon-plane','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055050010','material:demand:apply','需求提报','Demand Report',	2	,'055050',	10	,'material/demand/apply','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055050020','material:demand:tracking','需求跟踪','Demand Tracking',	2	,'055050',	20	,'material/demand/tracking','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055050030','material:demand:approve','需求校核','Demand Checking',	2	,'055050',	30	,'material/demand/approve','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055050040','material:demand:materiallist','航材需求清单','Material Demand List',	2	,'055050',	40	,'material/demand/materiallist','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055050050','material:demand:toollist','工具需求清单','Tool Demand List',	2	,'055050',	50	,'material/demand/toollist','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055900','material:file:hcmain','文档管理','Document Management',2,'055',990,'material/file/hcmain','','icon-archive','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055050060','material:return:apply','退料申请','Return Apply',	2	,'055050',	60	,'material/return/apply','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055050070','material:return:materiallist','航材退料清单','Material Return List',	2	,'055050',	70	,'material/return/materiallist','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055050080','material:return:toollist','工具退料清单','Tool Return List',	2	,'055050',	80	,'material/return/toollist','','','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055020','material:outin','出入库管理','Stock In/Out',  1  ,'055',  20  ,'','','icon-exchange','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055020010','material:outin:receipt','收货','Receipt',  2  ,'055020',  10  ,'material/outin/receipt','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055020020','material:outin:materialstockin','航材入库上架','Material Stock In',  2  ,'055020',  20  ,'material/outin/materialstockin','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055020030','material:outin:toolstockin','工具入库上架','Tool Stock In',  2  ,'055020',  30  ,'material/outin/toolstockin','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055020040','material:outin:stockout','出库','Stock Out',  2  ,'055020',  40  ,'material/outin/stockout','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055020050','material:outin:stockinoutlist','库存履历','Stock Resume',  2  ,'055020',  50  ,'material/outin/stockinoutlist','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055020060','material:toolborrowreturn:main','工具/设备借归','Tool Borrow/Return',  2  ,'055020',  60  ,'material/toolborrowreturn/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055020070','material:toolborrowreturnlist:main','工具/设备借归记录','Tool Borrow/Return List',  2  ,'055020',  70  ,'material/toolborrowreturnlist/main','','','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055030','material:contract','合同管理','Contract MGNT',  1  ,'055',  20  ,'','','icon-folder-open-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055030020','material:contract:mgnt','合同管理','Contract MGNT',  2  ,'055030',  20  ,'material/contract/mgnt','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055030030','material:contract:tracking','合同执行跟踪','Contract Execution Tracing',  2  ,'055030',  30  ,'material/contract/tracking','','','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055040','material:store:mgnt','航材库管理','Material Store MGNT',1  ,'055',40 ,'','','icon-building','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055040010','material:store:transfer','移库','Transfer',2 ,'055040',10  ,'material/store/transfer','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055040020','material:store:check:register','盘点盈亏登记','Check Register',2 ,'055040',20  ,'material/store/check/register','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055040030','material:store:check:list','盘点盈亏历史','Check List',2 ,'055040',30  ,'material/store/check/list','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055045','material:tool:store:mgnt','工具库管理','Tool Store MGNT',1 ,'055',45 ,'','','icon-wrench','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055045010','material:tool:store:transfer','移库','Transfer',2  ,'055045',10  ,'material/tool/store/transfer','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055045020','material:tool:store:check:register','盘点盈亏登记','Check Register',2  ,'055045',20  ,'material/tool/store/check/register','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055045030','material:tool:store:check:list','盘点盈亏历史','Check List',2  ,'055045',30  ,'material/tool/store/check/list','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055060','material:scrapped','报废管理','Scrapped MGNT',1 ,'055',60 ,'','','icon-trash','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055060010','material:scrapped:apply:main','报废申请','Scrapped Apply',2  ,'055060',10  ,'material/scrapped/apply/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055060020','material:scrapped:audit:main','报废审核','Scrapped Audit',2  ,'055060',20  ,'material/scrapped/audit/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055060030','material:destroy:airmaterial:main','航材销毁下架','Airmaterial Destroy',2  ,'055060',30  ,'material/destroy/airmaterial/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('055060040','material:destroy:tool:main','工具销毁下架','Tool Destroy',2  ,'055060',40  ,'material/destroy/tool/main','','','AMEMS');


--新生产计划
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025','produce','生产计划与控制管理','Produce Plan And Control',1,'0',null,'','25','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025010','aircraftinfo','飞机信息管理','Aircraft Info Mgnt',1,'025',10,'','','icon-plane','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025010010','aircraftinfo:main','飞机基本信息','Aircraft Basic Info',2,'025010',10,'aircraftinfo/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025010020','aircraftinfo:installationlist:main','飞机装机清单','Aircraft Installation List',2,'025010',20,'aircraftinfo/installationlist/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025020','aircraftinfo:status:main','飞机状态','Aircraft Status',2,'025',20,'aircraftinfo/status/main','','iconnew-planestate navigation-margintop','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025030','aircraftinfo:airworthiness:main','适航状态','Airworthiness',2,'025',30,'aircraftinfo/airworthiness/main','','iconnew-airworthiness navigation-margintop','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025040','produce:025040','生产监控','Production Monitoring',1,'025',40,'','','icon-desktop','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025040005','produce:monitorsetting:main','生产监控预警设置','Monitor Setting',2,'025040',5,'produce/monitorsetting/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025040010','produce:maintenance:initialization:main','维修计划初始化','Maintenance Initialization',2,'025040',10,'produce/maintenance/initialization/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025040020','produce:maintenance:monitoring:main','飞机维修监控','Aircraft Maintenance Monitoring',2,'025040',20,'produce/maintenance/monitoring/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025040030','produce:maintenance:forecast:main','飞机维修预测','Aircraft Maintenance Forecast',2,'025040',30,'produce/maintenance/forecast/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025040040','produce:warehouse:maintenance:monitoring:main','仓库部件维修监控','Component Maintenance Monitoring',2,'025040',40,'produce/warehouse/maintenance/monitoring/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025040050','produce:fault:monitoring:main','飞机故障监控','Fault Monitoring',2,'025040',50,'produce/fault/monitoring/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025040060','produce:maintenance:taskreplace:main','任务替代维护','Task Substitution',2,'025040',60,'produce/maintenance/taskreplace/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025050','produce:plan','维修计划','Maintenance Plan',1,'025',50,'','','iconnew-maintenanceplan navigation-margintop','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025050010','produce:maintenanceplan:main','维修计划','Maintenance Plan',2,'025050',10,'produce/maintenanceplan/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025050020','produce:maintenanceissuedplan:main','已下发计划','Issued Plan',2,'025050',20,'produce/maintenanceissuedplan/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025050030','produce:workpackage:main','工包管理135','Work Package 135',2,'025050',30,'produce/workpackage/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025050040','produce:workorder:main','例行工单135','Work Order 135',2,'025050',40,'produce/workorder/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025050060','produce:nrc135:main','非例行工单135','NRC 135',2,'025050',50,'produce/nrc135/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025060','produce:025060','客户项目管理','Customer And Project',1,'025',60,'','','icon-puzzle-piece','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025060010','baseinfo:customer:main','客户信息','Customer Info',2,'025060',10,'baseinfo/customer/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025060020','baseinfo:project:main','项目信息','Project Info',2,'025060',20,'baseinfo/project/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025070','produce:025070','执行控制','Customer And Project',1,'025',70,'','','icon-tasks','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025070010','produce:workpackage145:main','工包管理145','Work Package 145',2,'025070',10,'produce/workpackage145/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025070020','produce:workorder145:main','例行工单145','Work Order 145',2,'025070',20,'produce/workorder145/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025070030','produce:maintenanceplan145:main','维修计划145','Maintenance Plan',2,'025070',30,'produce/maintenanceplan145/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025070040','produce:preparation:main','生产准备','Production Preparation',2,'025070',40,'produce/preparation/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025070050','produce:workcardassessment:main','工卡评估','Work Card Assessment',2,'025070',50,'produce/workcardassessment/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025070060','produce:nrc145:main','非例行工单145','NRC 145',2,'025070',60,'produce/nrc145/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025080','produce:flb:main','飞行记录本','Flight Log Book',2,'025',80,'produce/flb/main','','iconnew-flightlog navigation-margintop','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx,remark) values ('025081','produce:flb2:main','飞行记录本','Flight Log Book',2,'025',81,'produce/flb2/main','','iconnew-flightlog navigation-margintop','AMEMS','HL');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025090','produce:025090','保留控制','Reservation Control',1,'025',90,'','','icon-warning-sign','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025090010','produce:reservation:fault:main','故障保留','DD',2,'025090',10,'produce/reservation/fault/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025090015','produce:reservation:fault:monitor','故障保留监控','DD Monitor',2,'025090',15,'produce/reservation/fault/monitor','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025090020','produce:reservation:item:main','项目保留','Item Reservation',2,'025090',20,'produce/reservation/item/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025090025','produce:reservation:item:monitor','项目保留监控','Item Reservation Monitor',2,'025090',25,'produce/reservation/item/monitor','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025090030','produce:reservation:defect:main','缺陷保留','Defect Reservation',2,'025090',30,'produce/reservation/defect/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025090035','produce:reservation:defect:monitor','缺陷保留监控','Defect Reservation',2,'025090',35,'produce/reservation/defect/monitor','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025100','produce:025100','履历管理','History',1,'025',100,'','','icon-list-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025100010','produce:taskhistory:main','历史任务','Task History',2,'025100',10,'produce/taskhistory/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025100020','produce:flighthistory:main','飞行履历','Flight History',2,'025100',20,'produce/flighthistory/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025100030','produce:componenthistory:main','部件履历','Component History',2,'025100',30,'produce/componenthistory/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025100035','produce:materialhistory:main','物料履历','Component History',2,'025100',35,'produce/materialhistory/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025100040','produce:componentiohistory:main','拆装记录','Component Change Record',2,'025100',40,'produce/componentiohistory/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025100050','produce:aircraftfailure:main','飞机故障履历','Aircraft Failure History',2,'025100',50,'produce/aircraftfailure/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025110','produce:025110','排班管理','Scheduling',1,'025',110,'','','icon-calendar','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025110010','produce:scheduling:person:main','人员排班','Crew Scheduling',2,'025110',10,'produce/scheduling/person/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025110020','produce:scheduling:aircraft:main','飞机排班','Aircraft Scheduling',2,'025110',20,'produce/scheduling/aircraft/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025120','produce:maintenancerecord:main','维修档案','Maintenance Record',2,'025',120,'produce/maintenancerecord/main','','icon-archive','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025900','produce:file:scmain','文档管理','Document Management',2,'025',990,'produce/file/scmain','','icon-archive','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025910','produce:worktimesubsidy:main','工时补贴统计','Work Time Subsidy',2,'025',910,'produce/worktimesubsidy/main','','icon-list-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('025920','produce:maintenancemgnt:monthlyreport','维修执管月报','Maintenance MGNT Report',2,'025',920,'produce/maintenancemgnt/monthlyreport','','icon-list-alt','AMEMS');

--质量管理
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040015','quality:015','授权管理','Post Authorization',  1  ,'040',  15  ,'','','','icon-plus-sign-alt','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040015010','quality:post:application:main','授权申请','Post Application',  2  ,'040015',  10  ,'quality/post/application/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040015020','quality:post:review:main','授权审核','Post Application Review',  2  ,'040015',  20  ,'quality/post/review/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040015030','quality:post:evaluation:main','授权评估','Post Application Evaluation',  2  ,'040015',  30  ,'quality/post/evaluation/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040015040','quality:post:expiry:monitor','授权控制','Post Expiry Monitoring',  2  ,'040015',  40  ,'quality/post/expiry/monitor','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040025','aerialmaterial:certificate:main','航材证书管理','Air Material Certificate',  2  ,'040',  25  ,'aerialmaterial/certificate/main','','','icon-trophy','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040200','quality:200','单机适航监控','Aircraft Airworthiness Monitor',  1  ,'040',  200  ,'','','','icon-camera','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040200010','quality:airworthiness:monitoring:main','CAD监控','CAD Monitor',  2  ,'040200',  10  ,'quality/airworthiness/monitoring/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040200015','quality:airworthiness:admonitoring:main','AD监控','AD Monitor',  2  ,'040200',  15  ,'quality/airworthiness/admonitoring/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040200020','quality:faultmonitoring:main','故障保留监控','DD Monitor',  2  ,'040200',  20  ,'quality/faultmonitoring/main','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040200030','quality:defectmonitoring:main','缺陷保留监控','Defect Reservation Monitor',  2  ,'040200',  30  ,'quality/defectmonitoring/main','','','','AMEMS');

insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040300','quality:300','执照有效监控','License Valid Monitor',  1  ,'040',  21  ,'','','','icon-camera','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040300010','quality:authorizationmonitor:list','维修执照监控','Maintenance License Monitor',  2  ,'040300',  10  ,'quality/authorizationmonitor/list','','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path,remark, fullorder, iconpath,xtlx) values ('040300020','quality:planemonitor:list','机型执照监控','Model Expiration Monitor',  2  ,'040300',  20  ,'quality/planemonitor/list','','','','AMEMS');

--客户项目管理
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('120','customerproject','客户项目管理','Customer Project',	1	,'0',	76	,'','76','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('120010','customerproject:customer:main','客户信息','Customer Info',2,'120',10,'customerproject/customer/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('120020','customerproject:project:main','项目信息','Project Info',2,'120',20,'customerproject/project/main','','','AMEMS');
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('120030','customerproject:maintenanceplan145:main','维修计划','Maintenance Plan',2,'120',30,'customerproject/maintenanceplan145/main','','','AMEMS');

--系统管理
insert into t_menu (id, menucode, menuname, menufname, menutype, parentid, menuorder, path, fullorder, iconpath,xtlx) values ('090140','sys:synrel:main','系统同步关系','Synchronous Relationship',2,'090',140,'sys/synrel/main','','icon-cloud','AMEMS');

--更新功能编码
update t_menu set gnbm = menuCode;